### ISSUE TITLE
生成app.json失败

### ISSUE THREAD

**Issue by yqchilde** [Tnze/CoolQ-Golang-Plugin#2]
![image](https://user-images.githubusercontent.com/36953759/71512159-f3b09a00-28cf-11ea-8dd4-bac672b0390d.png)

**Comment by Tnze** [comment]
看看你环境，执行下面命令看看输出
```bash
git --version
cqcfg -v
git rev-list --all --count
```

**Comment by yqchilde** [comment]
嗯。已解决，感谢回复------------------ 原始邮件 ------------------
发件人: "Tnze"<notifications@github.com>
发送时间: 2019年12月27日(星期五) 晚上11:38
收件人: "Tnze/CoolQ-Golang-Plugin"<CoolQ-Golang-Plugin@noreply.github.com>;
抄送: "yqchilde"<1455723643@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [Tnze/CoolQ-Golang-Plugin] 生成app.json失败 (#2)



看看你环境，执行下面命令看看输出
 git --version cqcfg -v git rev-list --all --count
 
&mdash;
